Phrases
=======
input: [""]
[word_atom(atom(ascii("")))]
--------
input: ["=??="]
[word_atom(atom(ascii("=??=")))]
--------
input: ["=????="]
[word_atom(atom(ascii("=????=")))]
--------
input: ["=?UTF-x?Q??="]
[word_atom(atom(ascii("=?UTF-x?Q??=")))]
--------
input: ["=?UTF-8?x??="]
[word_atom(atom(ascii("=?UTF-8?x??=")))]
--------
input: ["=?UTF-8?Q??="]
[word_atom(atom(ascii("")))]
--------
input: ["=?UTF-8?Q?a?="]
[word_atom(atom(ascii("a")))]
--------
input: ["=?UTF-8?Q?abc?="]
[word_atom(atom(ascii("abc")))]
--------
input: ["=?UTF-8?Q? ?="]
[word_quoted_string(quoted_string(ascii(" ")))]
--------
input: ["=?UTF-8?Q???="]
[word_atom(atom(ascii("?")))]
--------
input: ["=?UTF-8?Q?=?="]
[word_atom(atom(ascii("=?UTF-8?Q?=?=")))]
--------
input: ["=?UTF-8?Q?=x?="]
[word_atom(atom(ascii("=?UTF-8?Q?=x?=")))]
--------
input: ["=?UTF-8?Q?=xx?="]
[word_atom(atom(ascii("=?UTF-8?Q?=xx?=")))]
--------
input: ["=?UTF-8?Q?=A?="]
[word_atom(atom(ascii("=?UTF-8?Q?=A?=")))]
--------
input: ["=?UTF-8?Q?=00?="]
[word_atom(atom(ascii("=?UTF-8?Q?=00?=")))]
--------
input: ["=?UTF-8?Q?=09?="]
[word_quoted_string(quoted_string(ascii("\t")))]
--------
input: ["=?UTF-8?Q?=20?="]
[word_quoted_string(quoted_string(ascii(" ")))]
--------
input: ["=?UTF-8?Q?_?="]
[word_quoted_string(quoted_string(ascii(" ")))]
--------
input: ["=?UTF-8?Q?=5F?="]
[word_atom(atom(ascii("_")))]
--------
input: ["=?UTF-8?Q?é?="]
[word_atom(atom(ascii("=?UTF-8?Q?é?=")))]
--------
input: ["=?UTF-8?Q?=C3?="]
[word_atom(atom(ascii("=?UTF-8?Q?=C3?=")))]
--------
input: ["=?UTF-8?Q?=C3=A9?="]
[word_atom(atom(unicode("é")))]
--------
input: ["=?utf-8?q?=C3=A9?="]
[word_atom(atom(unicode("é")))]
--------
input: ["=?UTF-8*EN?Q?=C3=A9?="]
[word_atom(atom(unicode("é")))]
--------
input: ["=?UTF-8?Q?=22=C3=A9=22?="]
[word_quoted_string(quoted_string(unicode("\"é\"")))]
--------
input: ["=?UTF-8?Q?=e5=99=b8?="]
[word_atom(atom(unicode("噸")))]
--------
input: ["=?UTF-8?Q?caf?=", "=?UTF-8?Q?=C3=A9?="]
[word_atom(atom(unicode("café")))]
--------
input: ["=?UTF-8?Q?caf=C3?=", "=?UTF-8?Q?=A9?="]
[word_atom(atom(ascii("=?UTF-8?Q?caf=C3?="))), 
 word_atom(atom(ascii("=?UTF-8?Q?=A9?=")))]
--------
input: ["=?UTF-8?Q?h=C3=BA?=", "=?UTF-8?Q?h=C3=BA?=", "=?UTF-8?Q?h=C3=BA?="]
[word_atom(atom(unicode("húhúhú")))]
--------
input: ["=?UTF-8?Q?h=C3=BA?=", "hu", "=?UTF-8?Q?h=C3=BA?="]
[word_atom(atom(unicode("hú"))), word_atom(atom(ascii("hu"))), 
 word_atom(atom(unicode("hú")))]
--------
input: ["=?UTF-8?B??="]
[word_atom(atom(ascii("")))]
--------
input: ["=?UTF-8?B?=?="]
[word_atom(atom(ascii("")))]
--------
input: ["=?UTF-8?B?YQ==?="]
[word_atom(atom(ascii("a")))]
--------
input: ["=?UTF-8?B?YWI=?="]
[word_atom(atom(ascii("ab")))]
--------
input: ["=?UTF-8?B?YWJj?="]
[word_atom(atom(ascii("abc")))]
--------
input: ["=?UTF-8?B?Y*==?="]
[word_atom(atom(ascii("=?UTF-8?B?Y*==?=")))]
--------
input: ["=?UTF-8?B?YQ*=?="]
[word_atom(atom(ascii("=?UTF-8?B?YQ*=?=")))]
--------
input: ["=?UTF-8?B?AA==?="]
[word_atom(atom(ascii("=?UTF-8?B?AA==?=")))]
--------
input: ["=?UTF-8?B?gA==?="]
[word_atom(atom(ascii("=?UTF-8?B?gA==?=")))]
--------
input: ["=?UTF-8?B?w6k=?="]
[word_atom(atom(unicode("é")))]
--------
input: ["=?UTF-8?B?ww==?=", "=?UTF-8?B?qQ==?="]
[word_atom(atom(ascii("=?UTF-8?B?ww==?="))), 
 word_atom(atom(ascii("=?UTF-8?B?qQ==?=")))]
--------
input: ["=?UTF-8?B?Y2Fmw6k=?="]
[word_atom(atom(unicode("café")))]
--------
input: ["=?UTF-8?B?5Zm4?="]
[word_atom(atom(unicode("噸")))]
--------
input: ["=?UTF-8?B?Y2Fmw6k=?=", "=?UTF-8?Q?h=C3=BA?="]
[word_atom(atom(unicode("caféhú")))]
--------
input: ["=?UTF-8?B?Y2Fmw6k=?=", "=?UTF-8?Q?_h=C3=BA?="]
[word_quoted_string(quoted_string(unicode("café hú")))]
--------
input: ["=?ISO-8859-1?Q?caf=E9?="]
[word_atom(atom(unicode("café")))]
--------
input: ["=?ISO-8859-1?Q?=A4=A6=A8=B4=B8=BC=BD=BE?="]
[word_atom(atom(unicode("¤¦¨´¸¼½¾")))]
--------
input: ["=?ISO-8859-1?B?pKaotLi8vb4=?="]
[word_atom(atom(unicode("¤¦¨´¸¼½¾")))]
--------

Unstructured
============
«»
«»
--------
«=??=»
«=??=»
--------
«=????=»
«=????=»
--------
«=?UTF-x?Q??=»
«=?UTF-x?Q??=»
--------
«=?UTF-8?x??=»
«=?UTF-8?x??=»
--------
«=?UTF-8?Q??=»
«»
--------
«=?UTF-8?Q?a?=»
«a»
--------
«=?UTF-8?Q?abc?=»
«abc»
--------
«=?UTF-8?Q? ?=»
«=?UTF-8?Q? ?=»
--------
«=?UTF-8?Q???=»
«?»
--------
«=?UTF-8?Q?=?=»
«=?UTF-8?Q?=?=»
--------
«=?UTF-8?Q?=x?=»
«=?UTF-8?Q?=x?=»
--------
«=?UTF-8?Q?=xx?=»
«=?UTF-8?Q?=xx?=»
--------
«=?UTF-8?Q?=A?=»
«=?UTF-8?Q?=A?=»
--------
«=?UTF-8?Q?=00?=»
«=?UTF-8?Q?=00?=»
--------
«=?UTF-8?Q?=09?=»
«	»
--------
«=?UTF-8?Q?=20?=»
« »
--------
«=?UTF-8?Q?_?=»
« »
--------
«=?UTF-8?Q?=5F?=»
«_»
--------
«=?UTF-8?Q?é?=»
«=?UTF-8?Q?é?=»
--------
«=?UTF-8?Q?=C3?=»
«=?UTF-8?Q?=C3?=»
--------
«=?UTF-8?Q?=C3=A9?=»
«é»
--------
«=?utf-8?q?=C3=A9?=»
«é»
--------
«=?UTF-8*EN?Q?=C3=A9?=»
«é»
--------
«=?UTF-8?Q?=22=C3=A9=22?=»
«"é"»
--------
«=?UTF-8?Q?=e5=99=b8?=»
«噸»
--------
«=?UTF-8?Q?caf?= =?UTF-8?Q?=C3=A9?=»
«café»
--------
«=?UTF-8?Q?caf=C3?= =?UTF-8?Q?=A9?=»
«=?UTF-8?Q?caf=C3?= =?UTF-8?Q?=A9?=»
--------
«=?UTF-8?Q?h=C3=BA?= =?UTF-8?Q?h=C3=BA?= =?UTF-8?Q?h=C3=BA?=»
«húhúhú»
--------
«=?UTF-8?Q?h=C3=BA?= hu =?UTF-8?Q?h=C3=BA?=»
«hú hu hú»
--------
«=?UTF-8?B??=»
«»
--------
«=?UTF-8?B?=?=»
«»
--------
«=?UTF-8?B?YQ==?=»
«a»
--------
«=?UTF-8?B?YWI=?=»
«ab»
--------
«=?UTF-8?B?YWJj?=»
«abc»
--------
«=?UTF-8?B?Y*==?=»
«=?UTF-8?B?Y*==?=»
--------
«=?UTF-8?B?YQ*=?=»
«=?UTF-8?B?YQ*=?=»
--------
«=?UTF-8?B?AA==?=»
«=?UTF-8?B?AA==?=»
--------
«=?UTF-8?B?gA==?=»
«=?UTF-8?B?gA==?=»
--------
«=?UTF-8?B?w6k=?=»
«é»
--------
«=?UTF-8?B?ww==?= =?UTF-8?B?qQ==?=»
«=?UTF-8?B?ww==?= =?UTF-8?B?qQ==?=»
--------
«=?UTF-8?B?Y2Fmw6k=?=»
«café»
--------
«=?UTF-8?B?5Zm4?=»
«噸»
--------
«=?UTF-8?B?Y2Fmw6k=?= =?UTF-8?Q?h=C3=BA?=»
«caféhú»
--------
«=?UTF-8?B?Y2Fmw6k=?= =?UTF-8?Q?_h=C3=BA?=»
«café hú»
--------
«=?ISO-8859-1?Q?caf=E9?=»
«café»
--------
«=?ISO-8859-1?Q?=A4=A6=A8=B4=B8=BC=BD=BE?=»
«¤¦¨´¸¼½¾»
--------
«=?ISO-8859-1?B?pKaotLi8vb4=?=»
«¤¦¨´¸¼½¾»
--------
«  =?UTF-8?Q?h=C3=BA?= =?UTF-8?Q?h=C3=BA?= hu =?UTF-8?Q?h=C3=BA?=»
«  húhú hu hú»
--------
